function scenario = nondimensionalise(primary,secondary,params)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

Lsc   = primary.a;
musc  = 398600.4418;
Vsc   = sqrt(musc/Lsc);
Tsc   = Lsc/Vsc;
Asc   = Vsc/Tsc;
scale = diag([ones(3,1)./Lsc; ones(3,1)./Vsc]);

x_p     = scale*primary.x0;
x_s     = scale*secondary.x0;
r2ep    = rtn2eci(x_p(1:3),x_p(4:6));
r2es    = rtn2eci(x_s(1:3),x_s(4:6));
cov     = scale(1:3,1:3)*(r2ep*primary.C0(1:3,1:3)*r2ep'+r2es*secondary.C0(1:3,1:3)*r2es')*scale(1:3,1:3);
e2b     = eci2Bplane(primary.x0(4:6),secondary.x0(4:6)); 
e2b     = e2b([1 3],:);
Pb      = e2b*cov*e2b';
rb0     = e2b*(x_p(1:3)-x_s(1:3));
smd0    = dot(rb0,Pb\rb0);
T       = primary.T/Tsc;
HBR     = (primary.HBR + secondary.HBR)/Lsc;
smdLim  = PoC2SMD(Pb,HBR,params.pocLim, 5, 1, 1e-3, 200); 
md_lim  = params.md_lim_dim/Lsc;
ctrlMax = params.ctrlMax_dim/Asc;
t       = linspace(0,params.n_orb*2*pi/T,params.n_orb*params.nx_orb+1);

scenario = struct( ...
    't',        t, ...
    'x_p',      x_p, ...
    'x_s',      x_s, ...
    'cov',      cov, ...
    'Pb',       Pb, ...
    'rb0',      rb0, ...
    'smd0',     smd0, ...
    'ctrlMax',  ctrlMax, ...
    'T',        T, ...
    'HBR',      HBR, ...
    'smdLim',   smdLim, ...
    'md_lim',   md_lim, ...
    'Lsc',      Lsc, ...
    'Vsc',      Vsc, ...
    'Asc',      Asc, ...
    'Tsc',      Tsc ...
    );

end